// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = -1; // obj_Sonic
global.__objectDepths[1] = 0; // obj_walls
global.__objectDepths[2] = 0; // obj_switchablewalls
global.__objectDepths[3] = 0; // obj_bwalls
global.__objectDepths[4] = 0; // obj_fwalls
global.__objectDepths[5] = 0; // obj_stone_wall
global.__objectDepths[6] = 0; // obj_glass_wall
global.__objectDepths[7] = 0; // obj_grass_wall
global.__objectDepths[8] = 0; // obj_wood_wall
global.__objectDepths[9] = 0; // obj_metal_wall
global.__objectDepths[10] = 0; // obj_dirt_wall
global.__objectDepths[11] = 0; // obj_homable
global.__objectDepths[12] = 0; // obj_sonicparticle
global.__objectDepths[13] = 0; // obj_enemy
global.__objectDepths[14] = 0; // obj_rail
global.__objectDepths[15] = 0; // obj_hurting_object
global.__objectDepths[16] = 0; // obj_bridge
global.__objectDepths[17] = 0; // obj_enemy_nonbadnik
global.__objectDepths[18] = 0; // obj_switchable
global.__objectDepths[19] = 0; // obj_player_camera
global.__objectDepths[20] = 0; // obj_display_manager
global.__objectDepths[21] = 0; // obj_background_controller
global.__objectDepths[22] = -100; // obj_HUD_ingame
global.__objectDepths[23] = -1215752191; // obj_InverseColour
global.__objectDepths[24] = 0; // obj_input_controller
global.__objectDepths[25] = 0; // obj_title
global.__objectDepths[26] = 0; // obj_select_character
global.__objectDepths[27] = -1; // obj_titlescreen_spotlight
global.__objectDepths[28] = -5; // obj_titlescreen_logo
global.__objectDepths[29] = -7; // obj_titlescreen_controller
global.__objectDepths[30] = -8; // obj_pressstart_effect
global.__objectDepths[31] = -3; // obj_titlescreen_otherdetail
global.__objectDepths[32] = -100; // obj_qte_button
global.__objectDepths[33] = -100; // obj_qte_button_jumppanel
global.__objectDepths[34] = -100; // obj_qte2_button
global.__objectDepths[35] = -100; // obj_qte_fail
global.__objectDepths[36] = -100; // obj_qte_success
global.__objectDepths[37] = 0; // obj_qte3_buttons
global.__objectDepths[38] = 0; // obj_qte3_buttons_expert
global.__objectDepths[39] = 0; // obj_qte3_buttons_hard
global.__objectDepths[40] = -100; // obj_qte3_button
global.__objectDepths[41] = 0; // obj_musiccontroller
global.__objectDepths[42] = -80; // obj_titlecard_whiteblank_fadeout
global.__objectDepths[43] = -85; // obj_titlecard_blackblank_fadeout
global.__objectDepths[44] = -85; // obj_blackblank_fadein
global.__objectDepths[45] = -85; // obj_titlecard_SonicReady
global.__objectDepths[46] = -85; // obj_titlecard_SonicSet
global.__objectDepths[47] = -87; // obj_titlecard_SonicGo
global.__objectDepths[48] = -87; // obj_titlecard_card1
global.__objectDepths[49] = 0; // obj_titlecard_controller
global.__objectDepths[50] = -87; // obj_titlecard_SonicGo2
global.__objectDepths[51] = -86; // obj_titlecard_stagetitle
global.__objectDepths[52] = -90; // obj_titlecard_bestrank
global.__objectDepths[53] = -100; // obj_titlecard_new
global.__objectDepths[54] = -101; // obj_titlecard_character
global.__objectDepths[55] = 0; // obj_stagestat_controller
global.__objectDepths[56] = 0; // obj_stagetime
global.__objectDepths[57] = 0; // obj_checkpoint_controller
global.__objectDepths[58] = -80; // obj_checkpoint_info
global.__objectDepths[59] = 0; // obj_pause
global.__objectDepths[60] = 0; // obj_background_changer
global.__objectDepths[61] = 0; // obj_vibrate_xboxcontroller
global.__objectDepths[62] = 0; // obj_endmessage
global.__objectDepths[63] = -80; // obj_resultscreen_whitefadein
global.__objectDepths[64] = -110; // obj_resultscreen_blackfadein
global.__objectDepths[65] = -100; // obj_resultscreen
global.__objectDepths[66] = -105; // obj_result_rank
global.__objectDepths[67] = 0; // obj_t_background
global.__objectDepths[68] = 0; // obj_t_foreground
global.__objectDepths[69] = 0; // obj_t_switch
global.__objectDepths[70] = 0; // obj_t_switch2
global.__objectDepths[71] = 50; // obj_testzone_stone_wall
global.__objectDepths[72] = 50; // obj_testzone_glass_wall
global.__objectDepths[73] = 50; // obj_testzone_metal_wall
global.__objectDepths[74] = 50; // obj_testzone_wood_wall
global.__objectDepths[75] = 50; // obj_testzone_grass_wall
global.__objectDepths[76] = 50; // obj_testzone_dirt_wall
global.__objectDepths[77] = 50; // obj_testzone_slope
global.__objectDepths[78] = 50; // obj_testzone_slope30
global.__objectDepths[79] = 50; // obj_testzone_slope30f
global.__objectDepths[80] = 50; // obj_testzone_slope30b
global.__objectDepths[81] = 50; // obj_testzone_slope45
global.__objectDepths[82] = 50; // obj_testzone_slope_glass
global.__objectDepths[83] = 50; // obj_testzone_slope_metal
global.__objectDepths[84] = 50; // obj_testzone_slope_wood
global.__objectDepths[85] = 50; // obj_testzone_slope_grass
global.__objectDepths[86] = 50; // obj_testzone_slope_dirt
global.__objectDepths[87] = 50; // obj_testzone_slope_bwalls_metal
global.__objectDepths[88] = 50; // obj_testzone_pipelinedown
global.__objectDepths[89] = 50; // obj_testzone_pipelinedown_metal
global.__objectDepths[90] = 50; // obj_testzone_bwall
global.__objectDepths[91] = 50; // obj_bwalls_stone
global.__objectDepths[92] = 50; // obj_bwalls_metal
global.__objectDepths[93] = 50; // obj_bwalls_glass
global.__objectDepths[94] = 50; // obj_bwalls_grass
global.__objectDepths[95] = 50; // obj_bwalls_dirt
global.__objectDepths[96] = 50; // obj_bwalls_wood
global.__objectDepths[97] = 50; // obj_testzone_fwalls
global.__objectDepths[98] = 50; // obj_fwalls_stone
global.__objectDepths[99] = 50; // obj_fwalls_metal
global.__objectDepths[100] = 50; // obj_fwalls_glass
global.__objectDepths[101] = 50; // obj_fwalls_grass
global.__objectDepths[102] = 50; // obj_fwalls_dirt
global.__objectDepths[103] = 50; // obj_fwalls_wood
global.__objectDepths[104] = 50; // obj_testzone_wall
global.__objectDepths[105] = 50; // obj_bigloop
global.__objectDepths[106] = 50; // obj_testzone_pipeline
global.__objectDepths[107] = 50; // obj_testzone_bpipeline
global.__objectDepths[108] = 50; // obj_bigloop_b
global.__objectDepths[109] = 50; // obj_testzone_bpipelinedown
global.__objectDepths[110] = 50; // obj_testzone_fpipeline
global.__objectDepths[111] = 50; // obj_bigloop_f
global.__objectDepths[112] = 50; // obj_testzone_fpipelinedown
global.__objectDepths[113] = 50; // obj_testzone_rail
global.__objectDepths[114] = 50; // obj_testzone_rail_slope
global.__objectDepths[115] = 50; // obj_testzone_rail_pipeline
global.__objectDepths[116] = 50; // obj_testzone_rail_pipelinedown
global.__objectDepths[117] = 0; // obj_jumpfx
global.__objectDepths[118] = 0; // obj_boostfx
global.__objectDepths[119] = -10; // obj_hominglock
global.__objectDepths[120] = 0; // obj_trail
global.__objectDepths[121] = -10; // obj_stompfx
global.__objectDepths[122] = -2; // obj_boostsw
global.__objectDepths[123] = 0; // obj_grindspark
global.__objectDepths[124] = 0; // obj_spindash_dust
global.__objectDepths[125] = 0; // obj_sparkle_trail
global.__objectDepths[126] = 0; // obj_boostorb
global.__objectDepths[127] = 0; // obj_boostspeed_fx
global.__objectDepths[128] = 0; // obj_dashramp
global.__objectDepths[129] = 0; // obj_qte_dashramp
global.__objectDepths[130] = 0; // obj_qte2_dashramp
global.__objectDepths[131] = 0; // obj_qte3_dashramp
global.__objectDepths[132] = 0; // obj_qte3_dashramp_hard
global.__objectDepths[133] = 0; // obj_qte3_dashramp_expert
global.__objectDepths[134] = 0; // obj_dashring
global.__objectDepths[135] = 0; // obj_dashring_activate
global.__objectDepths[136] = 0; // obj_rainbowring
global.__objectDepths[137] = 0; // obj_rainbowring_activate
global.__objectDepths[138] = -10; // obj_dashring_outer
global.__objectDepths[139] = -10; // obj_rainbowring_outer
global.__objectDepths[140] = 0; // obj_swingboard
global.__objectDepths[141] = -5; // obj_swingbar
global.__objectDepths[142] = -12; // obj_water_surface
global.__objectDepths[143] = -11; // obj_water
global.__objectDepths[144] = -10; // obj_bubble
global.__objectDepths[145] = 15; // obj_corkscrew
global.__objectDepths[146] = -8; // obj_corkscrew_out
global.__objectDepths[147] = 0; // obj_wallstick
global.__objectDepths[148] = -10; // obj_4waycanon_ball
global.__objectDepths[149] = -9; // obj_4waycanon_sides
global.__objectDepths[150] = 0; // obj_ring
global.__objectDepths[151] = 0; // obj_rings10
global.__objectDepths[152] = 0; // obj_lightrings
global.__objectDepths[153] = 0; // obj_ring_scatter1
global.__objectDepths[154] = 0; // obj_ring_scatter2
global.__objectDepths[155] = 0; // obj_ringsparkle
global.__objectDepths[156] = 0; // obj_goalring
global.__objectDepths[157] = 0; // obj_explosion_small
global.__objectDepths[158] = 0; // obj_specialfx
global.__objectDepths[159] = 0; // obj_jumppanel_1
global.__objectDepths[160] = 0; // obj_jumppanel_2
global.__objectDepths[161] = 0; // obj_jumppanel_3
global.__objectDepths[162] = 0; // obj_jumppanel_4
global.__objectDepths[163] = 0; // obj_jumppanel_end
global.__objectDepths[164] = 0; // obj_jumppanel_parent
global.__objectDepths[165] = 0; // obj_wisp
global.__objectDepths[166] = 0; // obj_zombie_capsule
global.__objectDepths[167] = 0; // obj_zombiecapsule_destroyable
global.__objectDepths[168] = 2; // obj_bubble_capsule
global.__objectDepths[169] = 5; // obj_zombie_cyril_dummy
global.__objectDepths[170] = 5; // obj_zombie_nail_dummy
global.__objectDepths[171] = 5; // obj_monkey_dummy
global.__objectDepths[172] = -10; // obj_door
global.__objectDepths[173] = 30; // obj_switchdoor
global.__objectDepths[174] = 0; // obj_pit
global.__objectDepths[175] = 0; // obj_bomb
global.__objectDepths[176] = 0; // obj_cyril_axe
global.__objectDepths[177] = 0; // obj_spikeball
global.__objectDepths[178] = 0; // obj_spikes
global.__objectDepths[179] = 2; // obj_pulleyhandle
global.__objectDepths[180] = 1; // obj_pulleyend
global.__objectDepths[181] = 0; // obj_bridge16
global.__objectDepths[182] = 0; // obj_bridgenode
global.__objectDepths[183] = 0; // obj_zipline_start
global.__objectDepths[184] = 0; // obj_zipline_end
global.__objectDepths[185] = 0; // obj_zipline_pre
global.__objectDepths[186] = 0; // obj_autotunnel_start
global.__objectDepths[187] = 0; // obj_autotunnel_end
global.__objectDepths[188] = -5; // obj_dashpad
global.__objectDepths[189] = -5; // obj_dashpad_rail
global.__objectDepths[190] = 0; // obj_spring
global.__objectDepths[191] = 0; // obj_spring_egg
global.__objectDepths[192] = 0; // obj_spring_jumppanel
global.__objectDepths[193] = 0; // obj_checkpoint
global.__objectDepths[194] = 3; // obj_pitsign
global.__objectDepths[195] = 0; // obj_platform_move_h
global.__objectDepths[196] = 0; // obj_platform_move_v
global.__objectDepths[197] = 0; // obj_pole
global.__objectDepths[198] = 0; // obj_bungeechain
global.__objectDepths[199] = -2; // obj_bungeebox
global.__objectDepths[200] = 0; // obj_layerhider
global.__objectDepths[201] = 0; // obj_switch
global.__objectDepths[202] = 0; // obj_cpz_jump
global.__objectDepths[203] = 0; // obj_pullgrab
global.__objectDepths[204] = 0; // obj_eggspinner
global.__objectDepths[205] = 0; // obj_eggpawn_labour
global.__objectDepths[206] = 0; // obj_zombie_cyril
global.__objectDepths[207] = 0; // obj_zombie_bat
global.__objectDepths[208] = 0; // obj_zombie_monkey
global.__objectDepths[209] = 0; // obj_turtle_land
global.__objectDepths[210] = 0; // obj_turtle_fly
global.__objectDepths[211] = 0; // obj_flysquid
global.__objectDepths[212] = 0; // obj_enemycollider
global.__objectDepths[213] = -1; // obj_Shadow


global.__objectNames[0] = "obj_Sonic";
global.__objectNames[1] = "obj_walls";
global.__objectNames[2] = "obj_switchablewalls";
global.__objectNames[3] = "obj_bwalls";
global.__objectNames[4] = "obj_fwalls";
global.__objectNames[5] = "obj_stone_wall";
global.__objectNames[6] = "obj_glass_wall";
global.__objectNames[7] = "obj_grass_wall";
global.__objectNames[8] = "obj_wood_wall";
global.__objectNames[9] = "obj_metal_wall";
global.__objectNames[10] = "obj_dirt_wall";
global.__objectNames[11] = "obj_homable";
global.__objectNames[12] = "obj_sonicparticle";
global.__objectNames[13] = "obj_enemy";
global.__objectNames[14] = "obj_rail";
global.__objectNames[15] = "obj_hurting_object";
global.__objectNames[16] = "obj_bridge";
global.__objectNames[17] = "obj_enemy_nonbadnik";
global.__objectNames[18] = "obj_switchable";
global.__objectNames[19] = "obj_player_camera";
global.__objectNames[20] = "obj_display_manager";
global.__objectNames[21] = "obj_background_controller";
global.__objectNames[22] = "obj_HUD_ingame";
global.__objectNames[23] = "obj_InverseColour";
global.__objectNames[24] = "obj_input_controller";
global.__objectNames[25] = "obj_title";
global.__objectNames[26] = "obj_select_character";
global.__objectNames[27] = "obj_titlescreen_spotlight";
global.__objectNames[28] = "obj_titlescreen_logo";
global.__objectNames[29] = "obj_titlescreen_controller";
global.__objectNames[30] = "obj_pressstart_effect";
global.__objectNames[31] = "obj_titlescreen_otherdetail";
global.__objectNames[32] = "obj_qte_button";
global.__objectNames[33] = "obj_qte_button_jumppanel";
global.__objectNames[34] = "obj_qte2_button";
global.__objectNames[35] = "obj_qte_fail";
global.__objectNames[36] = "obj_qte_success";
global.__objectNames[37] = "obj_qte3_buttons";
global.__objectNames[38] = "obj_qte3_buttons_expert";
global.__objectNames[39] = "obj_qte3_buttons_hard";
global.__objectNames[40] = "obj_qte3_button";
global.__objectNames[41] = "obj_musiccontroller";
global.__objectNames[42] = "obj_titlecard_whiteblank_fadeout";
global.__objectNames[43] = "obj_titlecard_blackblank_fadeout";
global.__objectNames[44] = "obj_blackblank_fadein";
global.__objectNames[45] = "obj_titlecard_SonicReady";
global.__objectNames[46] = "obj_titlecard_SonicSet";
global.__objectNames[47] = "obj_titlecard_SonicGo";
global.__objectNames[48] = "obj_titlecard_card1";
global.__objectNames[49] = "obj_titlecard_controller";
global.__objectNames[50] = "obj_titlecard_SonicGo2";
global.__objectNames[51] = "obj_titlecard_stagetitle";
global.__objectNames[52] = "obj_titlecard_bestrank";
global.__objectNames[53] = "obj_titlecard_new";
global.__objectNames[54] = "obj_titlecard_character";
global.__objectNames[55] = "obj_stagestat_controller";
global.__objectNames[56] = "obj_stagetime";
global.__objectNames[57] = "obj_checkpoint_controller";
global.__objectNames[58] = "obj_checkpoint_info";
global.__objectNames[59] = "obj_pause";
global.__objectNames[60] = "obj_background_changer";
global.__objectNames[61] = "obj_vibrate_xboxcontroller";
global.__objectNames[62] = "obj_endmessage";
global.__objectNames[63] = "obj_resultscreen_whitefadein";
global.__objectNames[64] = "obj_resultscreen_blackfadein";
global.__objectNames[65] = "obj_resultscreen";
global.__objectNames[66] = "obj_result_rank";
global.__objectNames[67] = "obj_t_background";
global.__objectNames[68] = "obj_t_foreground";
global.__objectNames[69] = "obj_t_switch";
global.__objectNames[70] = "obj_t_switch2";
global.__objectNames[71] = "obj_testzone_stone_wall";
global.__objectNames[72] = "obj_testzone_glass_wall";
global.__objectNames[73] = "obj_testzone_metal_wall";
global.__objectNames[74] = "obj_testzone_wood_wall";
global.__objectNames[75] = "obj_testzone_grass_wall";
global.__objectNames[76] = "obj_testzone_dirt_wall";
global.__objectNames[77] = "obj_testzone_slope";
global.__objectNames[78] = "obj_testzone_slope30";
global.__objectNames[79] = "obj_testzone_slope30f";
global.__objectNames[80] = "obj_testzone_slope30b";
global.__objectNames[81] = "obj_testzone_slope45";
global.__objectNames[82] = "obj_testzone_slope_glass";
global.__objectNames[83] = "obj_testzone_slope_metal";
global.__objectNames[84] = "obj_testzone_slope_wood";
global.__objectNames[85] = "obj_testzone_slope_grass";
global.__objectNames[86] = "obj_testzone_slope_dirt";
global.__objectNames[87] = "obj_testzone_slope_bwalls_metal";
global.__objectNames[88] = "obj_testzone_pipelinedown";
global.__objectNames[89] = "obj_testzone_pipelinedown_metal";
global.__objectNames[90] = "obj_testzone_bwall";
global.__objectNames[91] = "obj_bwalls_stone";
global.__objectNames[92] = "obj_bwalls_metal";
global.__objectNames[93] = "obj_bwalls_glass";
global.__objectNames[94] = "obj_bwalls_grass";
global.__objectNames[95] = "obj_bwalls_dirt";
global.__objectNames[96] = "obj_bwalls_wood";
global.__objectNames[97] = "obj_testzone_fwalls";
global.__objectNames[98] = "obj_fwalls_stone";
global.__objectNames[99] = "obj_fwalls_metal";
global.__objectNames[100] = "obj_fwalls_glass";
global.__objectNames[101] = "obj_fwalls_grass";
global.__objectNames[102] = "obj_fwalls_dirt";
global.__objectNames[103] = "obj_fwalls_wood";
global.__objectNames[104] = "obj_testzone_wall";
global.__objectNames[105] = "obj_bigloop";
global.__objectNames[106] = "obj_testzone_pipeline";
global.__objectNames[107] = "obj_testzone_bpipeline";
global.__objectNames[108] = "obj_bigloop_b";
global.__objectNames[109] = "obj_testzone_bpipelinedown";
global.__objectNames[110] = "obj_testzone_fpipeline";
global.__objectNames[111] = "obj_bigloop_f";
global.__objectNames[112] = "obj_testzone_fpipelinedown";
global.__objectNames[113] = "obj_testzone_rail";
global.__objectNames[114] = "obj_testzone_rail_slope";
global.__objectNames[115] = "obj_testzone_rail_pipeline";
global.__objectNames[116] = "obj_testzone_rail_pipelinedown";
global.__objectNames[117] = "obj_jumpfx";
global.__objectNames[118] = "obj_boostfx";
global.__objectNames[119] = "obj_hominglock";
global.__objectNames[120] = "obj_trail";
global.__objectNames[121] = "obj_stompfx";
global.__objectNames[122] = "obj_boostsw";
global.__objectNames[123] = "obj_grindspark";
global.__objectNames[124] = "obj_spindash_dust";
global.__objectNames[125] = "obj_sparkle_trail";
global.__objectNames[126] = "obj_boostorb";
global.__objectNames[127] = "obj_boostspeed_fx";
global.__objectNames[128] = "obj_dashramp";
global.__objectNames[129] = "obj_qte_dashramp";
global.__objectNames[130] = "obj_qte2_dashramp";
global.__objectNames[131] = "obj_qte3_dashramp";
global.__objectNames[132] = "obj_qte3_dashramp_hard";
global.__objectNames[133] = "obj_qte3_dashramp_expert";
global.__objectNames[134] = "obj_dashring";
global.__objectNames[135] = "obj_dashring_activate";
global.__objectNames[136] = "obj_rainbowring";
global.__objectNames[137] = "obj_rainbowring_activate";
global.__objectNames[138] = "obj_dashring_outer";
global.__objectNames[139] = "obj_rainbowring_outer";
global.__objectNames[140] = "obj_swingboard";
global.__objectNames[141] = "obj_swingbar";
global.__objectNames[142] = "obj_water_surface";
global.__objectNames[143] = "obj_water";
global.__objectNames[144] = "obj_bubble";
global.__objectNames[145] = "obj_corkscrew";
global.__objectNames[146] = "obj_corkscrew_out";
global.__objectNames[147] = "obj_wallstick";
global.__objectNames[148] = "obj_4waycanon_ball";
global.__objectNames[149] = "obj_4waycanon_sides";
global.__objectNames[150] = "obj_ring";
global.__objectNames[151] = "obj_rings10";
global.__objectNames[152] = "obj_lightrings";
global.__objectNames[153] = "obj_ring_scatter1";
global.__objectNames[154] = "obj_ring_scatter2";
global.__objectNames[155] = "obj_ringsparkle";
global.__objectNames[156] = "obj_goalring";
global.__objectNames[157] = "obj_explosion_small";
global.__objectNames[158] = "obj_specialfx";
global.__objectNames[159] = "obj_jumppanel_1";
global.__objectNames[160] = "obj_jumppanel_2";
global.__objectNames[161] = "obj_jumppanel_3";
global.__objectNames[162] = "obj_jumppanel_4";
global.__objectNames[163] = "obj_jumppanel_end";
global.__objectNames[164] = "obj_jumppanel_parent";
global.__objectNames[165] = "obj_wisp";
global.__objectNames[166] = "obj_zombie_capsule";
global.__objectNames[167] = "obj_zombiecapsule_destroyable";
global.__objectNames[168] = "obj_bubble_capsule";
global.__objectNames[169] = "obj_zombie_cyril_dummy";
global.__objectNames[170] = "obj_zombie_nail_dummy";
global.__objectNames[171] = "obj_monkey_dummy";
global.__objectNames[172] = "obj_door";
global.__objectNames[173] = "obj_switchdoor";
global.__objectNames[174] = "obj_pit";
global.__objectNames[175] = "obj_bomb";
global.__objectNames[176] = "obj_cyril_axe";
global.__objectNames[177] = "obj_spikeball";
global.__objectNames[178] = "obj_spikes";
global.__objectNames[179] = "obj_pulleyhandle";
global.__objectNames[180] = "obj_pulleyend";
global.__objectNames[181] = "obj_bridge16";
global.__objectNames[182] = "obj_bridgenode";
global.__objectNames[183] = "obj_zipline_start";
global.__objectNames[184] = "obj_zipline_end";
global.__objectNames[185] = "obj_zipline_pre";
global.__objectNames[186] = "obj_autotunnel_start";
global.__objectNames[187] = "obj_autotunnel_end";
global.__objectNames[188] = "obj_dashpad";
global.__objectNames[189] = "obj_dashpad_rail";
global.__objectNames[190] = "obj_spring";
global.__objectNames[191] = "obj_spring_egg";
global.__objectNames[192] = "obj_spring_jumppanel";
global.__objectNames[193] = "obj_checkpoint";
global.__objectNames[194] = "obj_pitsign";
global.__objectNames[195] = "obj_platform_move_h";
global.__objectNames[196] = "obj_platform_move_v";
global.__objectNames[197] = "obj_pole";
global.__objectNames[198] = "obj_bungeechain";
global.__objectNames[199] = "obj_bungeebox";
global.__objectNames[200] = "obj_layerhider";
global.__objectNames[201] = "obj_switch";
global.__objectNames[202] = "obj_cpz_jump";
global.__objectNames[203] = "obj_pullgrab";
global.__objectNames[204] = "obj_eggspinner";
global.__objectNames[205] = "obj_eggpawn_labour";
global.__objectNames[206] = "obj_zombie_cyril";
global.__objectNames[207] = "obj_zombie_bat";
global.__objectNames[208] = "obj_zombie_monkey";
global.__objectNames[209] = "obj_turtle_land";
global.__objectNames[210] = "obj_turtle_fly";
global.__objectNames[211] = "obj_flysquid";
global.__objectNames[212] = "obj_enemycollider";
global.__objectNames[213] = "obj_Shadow";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for