#macro consPlayerNameSonic "Sonic"
#macro consPlayerNameShadow "Shadow"
#macro consPlayerNameTails "Tails"
#macro consPlayerActionSkid -4
#macro consPlayerActionLookUp -3
#macro consPlayerActionSpindashCharge -2
#macro consPlayerActionDuck -1
#macro consPlayerActionNormal 0
#macro consPlayerActionJump 1
#macro consPlayerActionRoll 2
#macro consPlayerActionHomingTarget 4
#macro consPlayerActionHomingNoTarget 4.5
#macro consPlayerActionSpringJump 5
#macro consPlayerActionDashRing 6
#macro consPlayerActionDashRamp 7
#macro consPlayerActionDashPad 8
#macro consPlayerActionSlide 9
#macro consPlayerActionTrick 10
#macro consPlayerActionGrinding 11
#macro consPlayerActionSwingBar 12
#macro consPlayerActionSwingBarJump 13
#macro consPlayerActionQTE 14
#macro consPlayerActionQTESucces 15
#macro consPlayerActionQTEFail 15.5
#macro consPlayerActionCorkscrew 16
#macro consPlayerActionCorkscrewRoll 17
#macro consPlayerActionStomp 18
#macro consPlayerActionWallHang 19
#macro consPlayerActionWallJump 20
#macro consPlayerAction4WayCanon 21
#macro consPlayerActionDamaged 22
#macro consPlayerActionLightRingDash 23
#macro consPlayerActionJumpPanelJump 24
#macro consPlayerActionJumpPanelLand 25
#macro consPlayerActionDead 26
#macro consPlayerActionPulley 27
#macro consPlayerActionChaosControl 28
#macro consPlayerActionPole 29
#macro consPlayerActionBungee 30
#macro consPlayerActionSuperTransformation 31
#macro consPlayerActionZipLineStart 32
#macro consPlayerActionZipLineTravel 32.5
#macro consPlayerActionPullGrab 33
#macro consPlayerActionAutoTunnel 34
